export enum PermissionEnum {
    CREATE_ACCOUNT = 'create_account',
    EDIT_ACCOUNT = 'edit_account',
    DETAIL_ACCOUNT = 'detail_account',
    LIST_ACCOUNT = 'list_account',
    CREATE_MEETING = 'create_meeting',
    EDIT_MEETING = 'edit_meeting',
    DETAIL_MEETING = 'detail_meeting',
    LIST_MEETING = 'list_meeting',
    DELETE_MEETING = 'delete_meeting',
    SEND_MAIL_TO_SHAREHOLDER = 'send_mail_to_shareholder',
    PARTICIPATE_MEETING = 'paticipate_meeting',
    VOTING_PROPOSAL = 'voting_proposal',
    EDIT_PROPOSAL = 'edit_proposal',
    DELETE_PROPOSAL = 'delete_proposal',
    LIST_PROPOSAL = 'list_poposal',
    LIST_USER_STATUS = 'list_user_status',
    LIST_ROLES = 'list_roles',
    LIST_PERMISSIONS = 'list_permissions',
    SETTING_PERMISSION_FOR_ROLES = 'setting_permission_for_roles',
    CREATE_ROLE = 'create_role',
    EDIT_PROFILE = 'edit_profile',
    DETAIL_PROFILE = 'detail_profile',
}
